name: Fetch localization data with SteamCMD

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:


jobs:
  check:
    name: Check for new updates
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: test `curl "https://api.steampowered.com/IGCVersion_570/GetClientVersion/v1/?key=${{secrets.STEAM_API_KEY}}" | jq ".result.active_version"` -ne `cat version`

  build:
    name: Fetch and build new source strings
    runs-on: ubuntu-latest
    needs: check
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - id: steamcmd
        uses: CyberAndrii/setup-steamcmd@v1
        
      - name: Install packages
        run: pip install vdf vpk

      - name: Fetch Dota2 client data
        run: steamcmd +login ${{secrets.STEAM_USERNAME}} ${{secrets.STEAM_PASSWORD}} +app_update 570 validate +quit

      - uses: mxschmitt/action-tmate@v3

      - name: Extract from client data
        run: python ./scripts/extract.py "${{ steps.steamcmd.outputs.directory }}/steamapps/common/dota 2 beta/"

      - name: Commit and Push
        run: |
          git config user.name "Nihongoka Bot"
          git config user.email "71134725+nihongoka-bot@users.noreply.github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Client version: $(<version)"
          git push origin master
